#!/bin/bash

# Nom du fichier JSON
JSON_FILE="files.json"

# Lire le fichier JSON pour extraire le nom de la classe principale et les fichiers auxiliaires
MAIN_FILE=$(jq -r '.main_file' "$JSON_FILE")

# Vérifier que le fichier principal existe
if [ -z "$MAIN_FILE" ] || [ ! -f "$MAIN_FILE" ]; then
  echo "Erreur: Fichier principal $MAIN_FILE non trouvé."
  exit 1
fi

# Créer le dossier build s'il n'existe pas
mkdir -p buildOutput

# Nom de l'exécutable basé sur le fichier principal
EXECUTABLE_NAME="buildOutput/$(basename "$MAIN_FILE" .c).exe"

# Compiler le projet avec gcc
./${EXECUTABLE_NAME} "$@"